print("#######################")
print("#                     #")
print("# Ahmad Reza Alfayiet #")
print("#    2210817210016    #")
print("#                     #")
print("#######################")